### ISSUE TITLE
Debian is missing "CPU INFO"

### ISSUE THREAD

**Issue by csirac2** [mikemaccana/rosetta-stone#18]
Which is also `/proc/cpuinfo`, like the other linuxen.

**Comment by csirac2** [comment]
I was going to make some other bugs regarding systemd commands (Eg. the portable way to write your scripts is still to use `logger` and `invoke-rc.d [verb] [service]`), but the systemd commands are perhaps sufficient for interactive admin.

**Comment by mikemaccana** [comment]
Sorted in #468f154be95266db08358a29c549bb47ccd77ae3. And yep, we try and use 'native' rather than 'portable' as a design goal.
