### ISSUE TITLE
Add instructions to run standalone in a browser

### ISSUE THREAD

**Issue by lloydde** [mikemaccana/rosetta-stone#3]
The "Building" steps end with generating the JSON. How do I generate the html and load in my browser?

**Comment by mikemaccana** [comment]
Browserify - but you're right I should add a demo so people can get it running stand-alone. Will sort out soon.

**Comment by bahamat** [comment]
It would be nice to add it to the `Makefile` too.

**Comment by mikemaccana** [comment]
Ok we have a `gulpfile` now, since #87706ae I'm generally happy with it.
