### ISSUE TITLE
Multiline code elements are displayed on a single line

### ISSUE THREAD

**Issue by bahamat** [mikemaccana/rosetta-stone#6]
E.g., the following code in `rosetta-stone.md`...

    pkgin av
    pkgin search

...in the browser renders as:

    pkgin av pkgin search

The rendered source in `rosetta-stone.js` is:

    <code>pkgin av\npkgin search\n</code>

Using `<pre>` instead of `<code>`, or nesting `<pre>` inside of `<code>` will properly format it in the browser.

**Comment by mikemaccana** [comment]
Ack. Should just be a matter of fixing newlines in Markdown. Will sort out shortly.

**Comment by bahamat** [comment]
No, I don't think that's going to work. The newlines are correct in Markdown. Even with blank lines in between each line, Markdown will render that as a single code block (so you'll get `\n\n`).

The only Markdown workaround would be to put HTML comments between each line to force breaking it into multiple `<code>` blocks.

E.g.:

        foo
    
    
    
        bar

Will render as:

    foo



    bar

But that will significantly uglify the Markdown code.

I this can be fixed in CSS though.

    code {
        white-space: pre-wrap;
        white-space: -moz-pre-wrap;
        white-space: -o-pre-wrap;
    }

**Comment by mikemaccana** [comment]
Cheers! Note there's no need for prefixes, autoprefixer does all these automatically.
